---
- name: Setup Web and Database Servers
  hosts: all
  become: true
  vars:
    app_name: laravel_app
    app_user: www-data
    app_group: www-data
    app_repo: "https://github.com/Practical-DevOps/app-for-devops"
    app_directory: /var/www/{{ app_name }}
    apache_conf: "/etc/apache2/sites-available/{{ app_name }}.conf"

  roles:
    - { role: server, when: "'server' in group_names" }
    - { role: db, when: "'db' in group_names" }
