---
- name: Install PostgreSQL
  apt:
    name: 
      - postgresql
    state: present
    update_cache: yes

- name: Install Python PostgreSQL library
  apt:
    name: python3-psycopg2
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Allow password authentication for PostgreSQL
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    regexp: "^local[[:space:]]+all[[:space:]]+postgres[[:space:]]+peer"
    line: "local   all             postgres                                md5"
    state: present
  notify: Restart PostgreSQL

- name: Create database
  postgresql_db:
    name: "{{ db_name }}"
    state: present

- name: Create database user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: "{{ db_name }}:ALL"

- name: Allow remote connections to PostgreSQL
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    line: "host    all             all             0.0.0.0/0            md5"
    state: present

- name: Configure PostgreSQL to listen on all interfaces
  lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*'"
  notify: Restart PostgreSQL
