---
- name: Start message
  ansible.builtin.debug:
    msg: 'Create task to install and prepare DB server'

- name: Install MariaDB and dependencies
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
    update_cache: yes

- name: Start MariaDB
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Set root password for MariaDB
  ansible.builtin.mysql_user:
    name: "{{ login_user }}"
    password: "{{ login_pass }}"
    login_user: "{{ login_user }}"
    login_password: "{{ root_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes

- name: Create application database
  ansible.builtin.mysql_db:
    name: "{{ db_name }}"
    state: present
    encoding: utf8
    login_user: "{{ login_user }}"
    login_password: "{{ login_pass }}"

- name: Create user for application
  ansible.builtin.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: "{{ db_name }}.*:ALL"
    host: '%'
    login_user: "{{ login_user }}"
    login_password: "{{ login_pass }}"
    state: present

- name: Add custom config for MariaDB
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: Restart MariaDB
