---
- name: Start message
  ansible.builtin.debug:
    msg: "Create task to deploy DB server and App server with Laravel"

- name: Add PHP repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP, Apache, and Node.js
  ansible.builtin.apt:
    name:
      - apache2
      - nodejs
      - php8.2
      - php8.2-cli
      - php8.2-curl
      - php8.2-bz2
      - php8.2-mbstring
      - php8.2-intl
      - php8.2-xml
      - php8.2-mysql

- name: Install Composer
  ansible.builtin.get_url:
    url: https://getcomposer.org/download/latest-stable/composer.phar
    dest: /usr/local/bin/composer
    mode: '0755'

- name: Clone the application repository
  ansible.builtin.git:
    repo: "{{ app_repo }}"
    dest: /tmp/app
    update: yes

- name: Copy application to server path
  ansible.builtin.copy:
    src: /tmp/app/
    dest: "{{ app_path }}"
    remote_src: yes

- name: Install application dependencies with Composer
  ansible.builtin.composer:
    command: install
    working_dir: "{{ app_path }}"
  environment:
    COMPOSER_ALLOW_SUPERUSER: 1

- name: Configure application environment
  ansible.builtin.template:
    src: app.conf.j2
    dest: "{{ app_path }}/.env"

- name: Enable Apache modules
  community.general.apache2_module:
    state: present
    name: rewrite

- name: Configure Apache
  ansible.builtin.template:
    src: apache.conf.j2
    dest: /etc/apache2/sites-available/app.conf

- name: Enable application site
  ansible.builtin.command:
    cmd: a2ensite app
  notify: Restart Apache
